### ISSUE TITLE
window clipping

### ISSUE THREAD

**Issue by KhaozFrost** [Eternita-S/XIVInstantMessenger#1]
could you add in window clipping to allow it to be brought higher up then other plugin windows??? so that it can essentially sit above plugins that are docked 
![image](https://user-images.githubusercontent.com/15788954/179420716-e919988f-4898-4f90-8f01-53cd8a0abdef.png)
![image](https://user-images.githubusercontent.com/15788954/179420723-255e0f55-1fe1-4eaa-9785-594969ef9a7f.png)
can see there how it just gets hidden behind chat 2 and peeping tom docked together

**Comment by Eternita-S** [comment]
an option to keep button on top was added in 1.1.0.9
